namespace TendexAI.Domain.Entities;

/// <summary>
/// Represents a message/reply in a support ticket conversation.
/// </summary>
public class SupportTicketMessage
{
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>
    /// The support ticket this message belongs to.
    /// </summary>
    public Guid SupportTicketId { get; set; }

    /// <summary>
    /// The user who sent this message.
    /// </summary>
    public Guid SenderUserId { get; set; }

    /// <summary>
    /// Name of the sender.
    /// </summary>
    public string SenderName { get; set; } = string.Empty;

    /// <summary>
    /// Whether the sender is an operator (true) or tenant user (false).
    /// </summary>
    public bool IsOperatorMessage { get; set; }

    /// <summary>
    /// Whether this message was generated by AI.
    /// </summary>
    public bool IsAiGenerated { get; set; }

    /// <summary>
    /// The message content.
    /// </summary>
    public string Content { get; set; } = string.Empty;

    /// <summary>
    /// Optional file attachment URL.
    /// </summary>
    public string? AttachmentUrl { get; set; }

    /// <summary>
    /// Optional file attachment name.
    /// </summary>
    public string? AttachmentName { get; set; }

    /// <summary>
    /// Whether the message has been read by the recipient.
    /// </summary>
    public bool IsRead { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    // Navigation property
    public SupportTicket SupportTicket { get; set; } = null!;
}
