using TendexAI.Domain.Common;

namespace TendexAI.Domain.Entities.Inquiries;

/// <summary>
/// Represents a draft response/answer to an inquiry.
/// Multiple drafts can exist (human and AI-generated) before a final answer is selected.
/// </summary>
public sealed class InquiryResponse : BaseEntity<Guid>
{
    private InquiryResponse() { } // EF Core constructor

    /// <summary>
    /// Factory method to create a new inquiry response draft.
    /// </summary>
    public static InquiryResponse Create(
        Guid inquiryId,
        string answerText,
        bool isAiGenerated,
        string createdBy)
    {
        return new InquiryResponse
        {
            Id = Guid.NewGuid(),
            InquiryId = inquiryId,
            AnswerText = answerText,
            IsAiGenerated = isAiGenerated,
            CreatedAt = DateTime.UtcNow,
            CreatedBy = createdBy
        };
    }

    /// <summary>Parent inquiry ID.</summary>
    public Guid InquiryId { get; private set; }

    /// <summary>The answer text.</summary>
    public string AnswerText { get; private set; } = null!;

    /// <summary>Whether this response was generated by AI.</summary>
    public bool IsAiGenerated { get; private set; }

    /// <summary>Confidence score if AI-generated (0-100).</summary>
    public int? AiConfidenceScore { get; private set; }

    /// <summary>AI model used if AI-generated.</summary>
    public string? AiModelUsed { get; private set; }

    /// <summary>Sources/references used by AI.</summary>
    public string? AiSources { get; private set; }

    /// <summary>Whether this draft was selected as the final answer.</summary>
    public bool IsSelected { get; private set; }

    // Navigation
    public Inquiry Inquiry { get; private set; } = null!;

    /// <summary>
    /// Mark this response as the selected final answer.
    /// </summary>
    public void MarkAsSelected(string selectedBy)
    {
        IsSelected = true;
        LastModifiedAt = DateTime.UtcNow;
        LastModifiedBy = selectedBy;
    }

    /// <summary>
    /// Set AI metadata for AI-generated responses.
    /// </summary>
    public void SetAiMetadata(int confidenceScore, string modelUsed, string? sources)
    {
        AiConfidenceScore = confidenceScore;
        AiModelUsed = modelUsed;
        AiSources = sources;
    }

    /// <summary>
    /// Update the answer text.
    /// </summary>
    public void UpdateText(string newText, string modifiedBy)
    {
        AnswerText = newText;
        LastModifiedAt = DateTime.UtcNow;
        LastModifiedBy = modifiedBy;
    }
}
